#!/usr/bin/env python3
"""Bundle the ESM web sources into one classic script for WKWebView.

WKWebView won't load `<script type="module">` over file:// (module scripts need a real origin /
CORS), so we keep render.mjs + app.mjs as ES modules for `node --test` and concatenate them into a
single classic `bundle.js` (no import/export) that the app loads via a plain <script> tag.
"""
from __future__ import annotations

import re
from pathlib import Path

WEB = Path(__file__).resolve().parent.parent / "app" / "web"


def strip_exports(src: str) -> str:
    # "export function f" -> "function f"; "export const X" -> "const X"; drop "export {…}" lines.
    src = re.sub(r"^export\s+(?=(function|const|let|class)\b)", "", src, flags=re.M)
    src = re.sub(r"^export\s*\{[^}]*\};?\s*$", "", src, flags=re.M)
    return src


def drop_imports(src: str) -> str:
    return re.sub(r'^\s*import\s+.*?;\s*$', "", src, flags=re.M)


def build() -> str:
    render = strip_exports((WEB / "render.mjs").read_text())
    app = drop_imports((WEB / "app.mjs").read_text())
    return ("// GENERATED by scripts/build-web.py — do not edit. Edit render.mjs / app.mjs.\n"
            '"use strict";\n(function () {\n' + render + "\n" + app + "\n})();\n")


def main() -> None:
    out = WEB / "bundle.js"
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
